language: php

php:
  - 7.2
  - 7.3

sudo: false
cache:
  directories:
      - $HOME/.composer/cache/files
      - $HOME/symfony-bridge/.phpunit

install: composer install

script: ./vendor/bin/simple-phpunit
